@echo off
cd /d "%~dp0"
echo Renaming 49 newsletter PDFs...

ren "REnews-Jan13.pdf" "alice-oldford-newsletter-january-2013.pdf"
ren "REnews-Feb13.pdf" "alice-oldford-newsletter-february-2013.pdf"
ren "REnews-Mar13.pdf" "alice-oldford-newsletter-march-2013.pdf"
ren "REnews-Apr13.pdf" "alice-oldford-newsletter-april-2013.pdf"
ren "REnews-May13.pdf" "alice-oldford-newsletter-may-2013.pdf"
ren "REnews-June13.pdf" "alice-oldford-newsletter-june-2013.pdf"
ren "REnews-July13.pdf" "alice-oldford-newsletter-july-2013.pdf"
ren "REnews-Aug13.pdf" "alice-oldford-newsletter-august-2013.pdf"
ren "REnews-Sep13.pdf" "alice-oldford-newsletter-september-2013.pdf"
ren "REnews-Oct13.pdf" "alice-oldford-newsletter-october-2013.pdf"
ren "REnews-Nov13.pdf" "alice-oldford-newsletter-november-2013.pdf"
ren "REnews-Dec13.pdf" "alice-oldford-newsletter-december-2013.pdf"
ren "REnews-Jan14.pdf" "alice-oldford-newsletter-january-2014.pdf"
ren "RENewsFeb14.pdf" "alice-oldford-newsletter-february-2014.pdf"
ren "REnews-Apr14.pdf" "alice-oldford-newsletter-april-2014.pdf"
ren "REnews-June14.pdf" "alice-oldford-newsletter-june-2014.pdf"
ren "REnews-July14.pdf" "alice-oldford-newsletter-july-2014.pdf"
ren "REnewsAug14.pdf" "alice-oldford-newsletter-august-2014.pdf"
ren "REnews-Sept14.pdf" "alice-oldford-newsletter-september-2014.pdf"
ren "REnews-Oct14.pdf" "alice-oldford-newsletter-october-2014.pdf"
ren "REnews-Nov14.pdf" "alice-oldford-newsletter-november-2014.pdf"
ren "REnews-Dec14.pdf" "alice-oldford-newsletter-december-2014.pdf"
ren "REnews-Feb15.pdf" "alice-oldford-newsletter-february-2015.pdf"
ren "REnews-Apr15.pdf" "alice-oldford-newsletter-april-2015.pdf"
ren "REnews-June15.pdf" "alice-oldford-newsletter-june-2015.pdf"
ren "REnews-Aug15.pdf" "alice-oldford-newsletter-august-2015.pdf"
ren "REnews-Sep15.pdf" "alice-oldford-newsletter-september-2015.pdf"
ren "REnews-Nov15.pdf" "alice-oldford-newsletter-november-2015.pdf"
ren "REnews-Jan16.pdf" "alice-oldford-newsletter-january-2016.pdf"
ren "REnews-Mar16.pdf" "alice-oldford-newsletter-march-2016.pdf"
ren "REnews-Apr16.pdf" "alice-oldford-newsletter-april-2016.pdf"
ren "REnews-May16.pdf" "alice-oldford-newsletter-may-2016.pdf"
ren "REnews-June16.pdf" "alice-oldford-newsletter-june-2016.pdf"
ren "REnews-July16.pdf" "alice-oldford-newsletter-july-2016.pdf"
ren "REnews-Dec16.pdf" "alice-oldford-newsletter-december-2016.pdf"
ren "REnews-Jan17.pdf" "alice-oldford-newsletter-january-2017.pdf"
ren "REnews-Feb17.pdf" "alice-oldford-newsletter-february-2017.pdf"
ren "RENews-March17.pdf" "alice-oldford-newsletter-march-2017.pdf"
ren "REnews-May17.pdf" "alice-oldford-newsletter-may-2017.pdf"
ren "REnews-Jun17.pdf" "alice-oldford-newsletter-june-2017.pdf"
ren "REnews-Aug17.pdf" "alice-oldford-newsletter-august-2017.pdf"
ren "REnews-Feb18.pdf" "alice-oldford-newsletter-february-2018.pdf"
ren "REnews-April18.pdf" "alice-oldford-newsletter-april-2018.pdf"
ren "REnewsJune18.pdf" "alice-oldford-newsletter-june-2018.pdf"
ren "RENewsAug18.pdf" "alice-oldford-newsletter-august-2018.pdf"
ren "RENewsOct18.pdf" "alice-oldford-newsletter-october-2018.pdf"
ren "RENewsApr19.pdf" "alice-oldford-newsletter-april-2019.pdf"
ren "RENewsMay19.pdf" "alice-oldford-newsletter-may-2019.pdf"
ren "RENewsSept19.pdf" "alice-oldford-newsletter-september-2019.pdf"

echo Done! All files renamed.
pause